# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f44f452833137175e5c09f2536f541b538f82f5c0606e0d2a8036de7322df1fbe59ce13ac3570497ed4c32a19cf78b9a5dbd25359b7ed89dafc90f920ced673d

test:
  secret_key_base: e7e692ab8719fed8cfac3a711784f7e24baed7625dfe7637331e93ce03d846e4681335a263eb64eb7982d664223d0eda32fa7d0e45f01a67b8f99c5dde6a9618

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
